### PR TITLE
Update recipe version to 1.0.0 and corresponding sha256

### PR DESCRIPTION
**Pull request by allanleal**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by allanleal** [comment]
@conda-forge-admin, please rerender

**Comment by JohanMabille** [comment]
the target file is now installed in `share/cmake` instead of `lib/cake`, the tests should be updated.

**Comment by allanleal** [comment]
@JohanMabille , we should be good to go now. Let me know if you agree.

**Comment by JohanMabille** [comment]
Nice! Thanks.

**Pull request merged**
